language: node_js
node_js:
    - "4.0"
script:
    - npm install
    - gulp sass
    - gulp jsx-build
install:
    - npm install -g firebase-tools
    - npm install -g gulp
after_success:
    - firebase deploy --token $REACTDEMO